# -*- coding: utf-8 -*-
"""BioCompiler - DNA Transcriber e RNA Processor."""

from .core import (
    BioCompiler,
    AnalysisResult,
    classify,
    validate_dna,
    find_start_codon,
    find_stop_codon,
    RESULT_CORRECT,
    RESULT_INVALID_BASE,
    RESULT_MISSING_START,
    RESULT_MISSING_STOP,
    RESULT_FRAMESHIFT,
    RESULT_NONSENSE,
)
from .transcriber import transcribe, translate, translate_codons, GENETIC_CODE

from .rna_processor import (
    BioCompiler2,
    Intron,
    RnaMaturationResult,
    clean_rna_sequence,
    validate_rna,
    find_first_valid_intron,
    splice_introns,
    mature_pre_mrna,
    classify_premrna,
    CAP_5_MARKER,
    POLY_A_LENGTH,
    POLY_A_TAIL,
    RESULT_RNA_CORRECT,
    RESULT_RNA_INVALID_BASE,
    RESULT_MISSING_5_SITE,
    RESULT_MISSING_3_SITE,
    RESULT_BRANCH_POINT,
)

__all__ = [
    "BioCompiler",
    "AnalysisResult",
    "classify",
    "validate_dna",
    "find_start_codon",
    "find_stop_codon",
    "RESULT_CORRECT",
    "RESULT_INVALID_BASE",
    "RESULT_MISSING_START",
    "RESULT_MISSING_STOP",
    "RESULT_FRAMESHIFT",
    "RESULT_NONSENSE",
    "transcribe",
    "translate",
    "translate_codons",
    "GENETIC_CODE",
    "BioCompiler2",
    "Intron",
    "RnaMaturationResult",
    "clean_rna_sequence",
    "validate_rna",
    "find_first_valid_intron",
    "splice_introns",
    "mature_pre_mrna",
    "classify_premrna",
    "CAP_5_MARKER",
    "POLY_A_LENGTH",
    "POLY_A_TAIL",
    "RESULT_RNA_CORRECT",
    "RESULT_RNA_INVALID_BASE",
    "RESULT_MISSING_5_SITE",
    "RESULT_MISSING_3_SITE",
    "RESULT_BRANCH_POINT",
]
